[package]
name = "bevy_mod_picking"
version = "0.3.3-alpha.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A 3D mouse picking plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "graphics", "picking", "bevy", "3d"]
categories = ["game-engines", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4", default-features = false, features = ["render"] }
log = "0.4.11"
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "master", default-features = false, features = ["render"] }

[features]
example_deps = [ "bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf" ]

[[example]]
name = "3d_scene"
required-features = [ "example_deps" ]

[[example]]
name = "events"
required-features = [ "example_deps" ]

[[example]]
name = "multiple_windows"
required-features = [ "example_deps" ]

[[example]]
name = "stress_test"
required-features = [ "example_deps" ]
